image:
  file: .gitpod.Dockerfile

tasks:
  - name: Env
  - init: |
      lua -v
      luarocks -v
      ao --version
  
  - name: 🛠📊 Build GraphQL aos Module
    init: |
      mkdir build && \
        cd build && \
        cmake .. && \
        make



