image:
  file: .gitpod.Dockerfile

tasks:
  - name: Env
  - init: |
      lua -v
      luarocks -v
      ao --version
  
  - name: 🛠📊 Build & Start GraphQL Module
    init: |
      npm i
      npm run build:sandbox
    command: 
      npm start

vscode:
  extensions:
    - "standard.vscode-standard"
